### PR TITLE
Add token refresh support

### PR DESCRIPTION
**Pull request by enolfc**
* Simplify code by using features in oauthenticator
* Add token refresh method

### CODE REVIEW

**Comment by andrea-manzi** [comment]
i'm getting this error now

`[C 2020-07-14 10:00:31.450 JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f845f17a940> instance must be a type, but 'oauthenticator.egicheckin.EGICheckinAuthenticator' could not be imported`

has the name of the class changed?

**Comment by enolfc** [comment]
> i'm getting this error now
> 
> `[C 2020-07-14 10:00:31.450 JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f845f17a940> instance must be a type, but 'oauthenticator.egicheckin.EGICheckinAuthenticator' could not be imported`
> 
> has the name of the class changed?

Yes, different python package: `egiauthenticator.egicheckin.EGICheckinAuthenticator`

**Comment by andrea-manzi** [comment]
ok, now i see this error

    
```
[I 2020-07-14 10:36:12.864 JupyterHub log:174] 302 GET /hub/spawn -> /hub/login?next=%2Fhub%2Fspawn (@10.42.0.0) 284.93ms
[E 2020-07-14 10:36:13.403 JupyterHub base:431] Error getting current user
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 426, in get_current_user
        user = await self.refresh_auth(user)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 331, in refresh_auth
        auth_info = await self.authenticator.refresh_user(user, self)
      File "/usr/local/lib/python3.6/dist-packages/egiauthenticator/egicheckin.py", line 170, in refresh_user
        resp = await http_client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 401: Unauthorized
```

i don't know if something else on the conf has to be updated

**Comment by andrea-manzi** [comment]
not needed anymore

**Pull request closed without merging**
